# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: WildByDesign.WDACTrayTool
PackageVersion: 6.0.2
PackageLocale: en-US
Publisher: WildByDesign
PublisherUrl: https://github.com/WildByDesign
PublisherSupportUrl: https://github.com/WildByDesign/WDACTrayTool/issues
PackageName: App Control Tray & Policy Manager
PackageUrl: https://github.com/WildByDesign/WDACTrayTool
License: GPL-3.0
LicenseUrl: https://github.com/WildByDesign/WDACTrayTool/blob/HEAD/LICENSE
ShortDescription: System Tray Tool for WDAC.
ReleaseNotes: |-
  Policy Manager:
  - Fixed ListView checkboxes in dark mode
ReleaseNotesUrl: https://github.com/WildByDesign/WDACTrayTool/releases/tag/6.0.2
ManifestType: defaultLocale
ManifestVersion: 1.10.0
