# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.MDEClientAnalyzer
PackageVersion: 2024.5.8
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Microsoft Defender for Endpoint Client Analyzer
License: Proprietary
ShortDescription: The Microsoft Defender for Endpoint Client Analyzer (MDECA) can be useful when diagnosing sensor health or reliability issues on onboarded devices.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
