# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.ClientSpy
PackageVersion: 5.0.9128.1007
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: CliSpy.exe
  PortableCommandAlias: CliSpy
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://winget.tplant.com.au/download/m/Microsoft/ConfigMgr/ClientTools/5.0.9128.1007/ClientTools.zip
  InstallerSha256: 40765ED149B881189BFF25CA7ABAF260AC0C243C40CD60A9FC80460B89874B23
ManifestType: installer
ManifestVersion: 1.10.0
