# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.Azure.BatchExplorer
PackageVersion: 2.22.0
InstallerLocale: en-US
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: ef4dcbd6-f9d0-51ec-ae84-09c95245167d
ReleaseDate: 2024-12-06
AppsAndFeaturesEntries:
- DisplayName: BatchExplorer 2.22.0-stable.1076
  DisplayVersion: 2.22.0-stable.1076
  ProductCode: ef4dcbd6-f9d0-51ec-ae84-09c95245167d
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Azure/BatchExplorer/releases/download/v2.22.0-stable.1076/BatchExplorer.Setup.2.22.0-stable.1076.exe
  InstallerSha256: 0CC6FD6E593617DB33FC57CC7C67B3E28232A61CEEA5D3DAB4A4DA8A78498724
ManifestType: installer
ManifestVersion: 1.9.0
