# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.Azure.BatchExplorer
PackageVersion: 2.22.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: BatchExplorer
License: MIT
Copyright: Copyright Â© 2024 Microsoft Corporation
ShortDescription: A client tool to help create, debug and monitor Azure Batch Applications.
Tags:
- angular2
- azure
- azure-batch
- cloud
- electron
- typescript
- ui
ManifestType: defaultLocale
ManifestVersion: 1.9.0
