# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Microsoft.EventLogExpert
PackageVersion: 25.6.10.147
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
