# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.ClientTools
PackageVersion: 5.0.9141.1002
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
