# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.Azure.BatchExplorer
PackageVersion: 2.22.0-stable.1076
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://github.com/Azure
PublisherSupportUrl: https://github.com/Azure/BatchExplorer/issues
PackageName: BatchExplorer
PackageUrl: https://github.com/Azure/BatchExplorer
License: MIT
LicenseUrl: https://github.com/Azure/BatchExplorer/blob/HEAD/LICENSE
Copyright: Copyright Â© 2024 Microsoft Corporation
ShortDescription: A client tool to help create, debug and monitor Azure Batch Applications.
Tags:
- angular2
- azure
- azure-batch
- cloud
- electron
- typescript
- ui
ReleaseNotes: |-
  Changes:
  - 71b4b69 Merge pull request #2960 from Azure/main
  - 4a73c20 Juno: check in to users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240901120711551. (#2930)
  - 9f168f1 Updated changelog and version. (#2959)
  - 46a58ea Merge pull request #2953 from Azure/shpaster/remove-python
  - 8b7984d Removes Gallery-specific code
  - a37d9b6 Remove more Python-related code / licenses
  - 71a5dae Fixes file navigator directory uploading
  - 9cca636 Removes the Gallery from navigation
  - 009f7ec Fixes empty UI error alerts
  - 5804b72 Removes Python from Batch Explorer
  See More
  - 13d0324 Bump max listeners for form event emitters (#2952)
  - 9ad143e Merge pull request #2950 from Azure/release/merge-stable
  - 15246da Bumps Batch Explorer development to version 2.22.0
  - eed3aa5 Merge branch 'stable' into main
  This list of changes was auto generated.
ReleaseNotesUrl: https://github.com/Azure/BatchExplorer/releases/tag/v2.22.0-stable.1076
ManifestType: defaultLocale
ManifestVersion: 1.10.0
