# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: WildByDesign.WDACTrayTool
PackageVersion: 6.0.3
PackageLocale: en-US
Publisher: WildByDesign
PublisherUrl: https://github.com/WildByDesign
PublisherSupportUrl: https://github.com/WildByDesign/WDACTrayTool/issues
PackageName: App Control Tray & Policy Manager
PackageUrl: https://github.com/WildByDesign/WDACTrayTool
License: GPL-3.0
LicenseUrl: https://github.com/WildByDesign/WDACTrayTool/blob/HEAD/LICENSE
ShortDescription: System Tray Tool for WDAC.
ReleaseNotes: This release properly handles the false positive from Microsoft Windows Defender.
ReleaseNotesUrl: https://github.com/WildByDesign/WDACTrayTool/releases/tag/6.0.3
ManifestType: defaultLocale
ManifestVersion: 1.10.0
