# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: WildByDesign.WDACTrayTool
PackageVersion: 6.0.3
InstallerType: zip
ReleaseDate: 2025-06-25
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/WildByDesign/WDACTrayTool/releases/download/6.0.3/AppControlTray-6.0.3.zip
  InstallerSha256: 768CE2C15B6EBD6C6A25E157E257AC3BDC4C852B99FE19CD3E97442934FDC416
ManifestType: installer
ManifestVersion: 1.10.0
