# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.Kusto.Explorer
PackageVersion: 1.0.3.1526
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Kusto.Explorer
PackageUrl: https://aka.ms/ke
License: Proprietary
ShortDescription: Kusto.Explorer allows you to query and analyze your data with Kusto Query Language (KQL) in a user-friendly interface.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
