# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.AppVerifier
PackageVersion: 10.1.26100.3624
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://winget.tplant.com.au/download/m/Microsoft/WindowsSDK/AppVerifier/10.1.26100.3624/Application%20Verifier%20x86%20External%20Package%20(DesktopEditions)-x86_en-us.msi
  InstallerSha256: C24752A7C0596FDD9EE341B4FD98FCC16DA70CC95B8C88A35CBF3BE15C1F6097
  ProductCode: '{ECBCBFF8-7D69-26E2-A179-A03ADBE8304C}'
  AppsAndFeaturesEntries:
  - DisplayName: Application Verifier x86 External Package (DesktopEditions)
    Publisher: Microsoft
    ProductCode: '{ECBCBFF8-7D69-26E2-A179-A03ADBE8304C}'
    UpgradeCode: '{DF1118C5-3130-A1E3-0699-F751D09373DD}'
- Architecture: x64
  InstallerUrl: https://winget.tplant.com.au/download/m/Microsoft/WindowsSDK/AppVerifier/10.1.26100.3624/Application%20Verifier%20x64%20External%20Package%20(DesktopEditions)-x64_en-us.msi
  InstallerSha256: CF27CD7F45EAF54D80B810AA1BA21B49B9692B186F400EAB065DF71D84F5894F
  ProductCode: '{1C3A7956-CF45-9F79-3D8D-C85D3C294DB5}'
  AppsAndFeaturesEntries:
  - DisplayName: Application Verifier x64 External Package (DesktopEditions)
    Publisher: Microsoft
    ProductCode: '{1C3A7956-CF45-9F79-3D8D-C85D3C294DB5}'
    UpgradeCode: '{E4E1A3E4-E154-E02D-FFC1-F8FAEC50AA28}'
- Architecture: arm64
  InstallerUrl: https://winget.tplant.com.au/download/m/Microsoft/WindowsSDK/AppVerifier/10.1.26100.3624/Application%20Verifier%20arm64%20External%20Package%20(DesktopEditions)-arm64_en-us.msi
  InstallerSha256: 2B89CCAF2AB26DD7F113F453AFE14EDE79FB6D0A348A2986AA653614A8AB1DBE
  ProductCode: '{3BBCD068-2020-8046-35F2-FFB013DF0C18}'
  AppsAndFeaturesEntries:
  - DisplayName: Application Verifier arm64 External Package (DesktopEditions)
    Publisher: Microsoft
    ProductCode: '{3BBCD068-2020-8046-35F2-FFB013DF0C18}'
    UpgradeCode: '{D9DACB15-4D98-FAFE-B5CA-C565A8F96FE9}'
ManifestType: installer
ManifestVersion: 1.9.0
