# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.AppVerifier
PackageVersion: 10.1.26100.3624
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Windows Application Verifier
PackageUrl: https://go.microsoft.com/fwlink/?linkid=2320054
License: Proprietary
ShortDescription: Application Verifier (AppVerifier) is a runtime verification tool for unmanaged code that assists in finding subtle programming errors, security issues and limited user account privilege problems.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
