# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.AppVerifier
PackageVersion: 10.1.26100.3624
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
