# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.MissionAppsCLI
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Mission Apps CLI
License: Proprietary
ShortDescription: This tool is used for deploying Mission App workloads.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
