# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.IdFix
PackageVersion: 2.6.0.3
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: IdFix
License: MIT
ShortDescription: IdFix is used to perform discovery and remediation of identity objects and their attributes in an on-premises Active Directory environment in preparation for migration to Azure Active Directory.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
