# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.PolicySpy
PackageVersion: 5.0.9128.1007
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: ConfigMgr Policy Spy
PackageUrl: https://go.microsoft.com/fwlink/?linkid=2237687
License: Proprietary
Copyright: Copyright (C) Microsoft Corporation. All rights reserved.
ShortDescription: Policy Spy is one of the Configuration Manager tools. It's a tool for viewing and troubleshooting the policy system on Configuration Manager clients.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
