# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.PolicySpy
PackageVersion: 5.0.9128.1007
InstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2025-04-17
Installers:
- Architecture: x86
  InstallerUrl: https://winget.tplant.com.au/download/m/Microsoft/ConfigMgr/PolicySpy/5.0.9128.1007/PolicySpy.exe
  InstallerSha256: DF613A8498AECC985123E54D7FF1B05909DD16BA2EE9E5120891467187CF7665
ManifestType: installer
ManifestVersion: 1.9.0
