# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.EventLogExpert
PackageVersion: 25.12.11.1105
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://github.com/microsoft
PublisherSupportUrl: https://github.com/microsoft/EventLogExpert/issues
PackageName: EventLogExpert
PackageUrl: https://github.com/microsoft/EventLogExpert
License: MIT
LicenseUrl: https://github.com/microsoft/EventLogExpert/blob/HEAD/LICENSE
ShortDescription: A Windows Event Log viewer for tech support and IT professionals.
Tags:
- event-log-expert
- evtx-files
- windows-event-log-viewer
- windowseventlogviewer
ReleaseNotes: |-
  Changes:
  - fa501e3 Fixed issue with extension casing
  - 54c809f Made required changes to event db tool to support the command line release package changes
  - 9b5dcdf Updated projects to .NET 10 along with package dependencies
  This list of changes was auto generated.
ReleaseNotesUrl: https://github.com/microsoft/EventLogExpert/releases/tag/v25.12.11.1105
ManifestType: defaultLocale
ManifestVersion: 1.10.0
