# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.Intune.WSLPlugin
PackageVersion: 1.25.4.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Intune WSL Plugin
License: MIT
ShortDescription: The Intune WSL plugin can be used to manage WSL distros through Windows Custom Compliance Policies and Settings.
Tags:
  - app-management
  - bash
  - intune
  - line-of-business
  - macos
  - shell-scripting
ManifestType: defaultLocale
ManifestVersion: 1.9.0
