# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Microsoft.GlobalSecureAccessClient
PackageVersion: 2.14.80.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
