# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.GlobalSecureAccessClient
PackageVersion: 2.14.80.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Global Secure Access Client
License: Proprietary
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription: The Global Secure Access client allows organizations control over network traffic at the end-user computing device.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
