# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: jason4tw.UIPlusPlus
PackageVersion: 3.0.3.0
PackageLocale: en-US
Publisher: Jason Sandys
PackageName: UI++
License: GPL-3.0
ShortDescription: UI++ is a dynamic user interface (UI) generation tool.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
