# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: jason4tw.UIPlusPlus
PackageVersion: 3.0.3.0
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/jason4tw/UIPlusPlus/raw/refs/heads/main/Binary%20Archive/UI++3.0.3.0.zip
  InstallerSha256: F6965C18F0B7438F170E6BDD0818AD83BDB364281A198DD553B484D92544BCF7
  NestedInstallerFiles:
  - RelativeFilePath: 3.0.3.0\x86\UI.exe
- Architecture: x64
  InstallerUrl: https://github.com/jason4tw/UIPlusPlus/raw/refs/heads/main/Binary%20Archive/UI++3.0.3.0.zip
  InstallerSha256: F6965C18F0B7438F170E6BDD0818AD83BDB364281A198DD553B484D92544BCF7
  NestedInstallerFiles:
  - RelativeFilePath: 3.0.3.0\x64\UI++64.exe
ManifestType: installer
ManifestVersion: 1.9.0
