# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Pantaray.SuperOrca
PackageVersion: 11.0.0.1
PackageLocale: en-US
Publisher: Pantaray Research Ltd.
PackageName: QSetup Installation Suite
License: Proprietary
Copyright: Copyright (C) 2002-2012, Pantaray Research Ltd.
ShortDescription: SuperOrca from "Pantaray Research Ltd." is a direct replacement to the "Orca" MSI Editor from Microsoft. SuperOrca may be used to examine and modify an MSI database in order to distribute a new MSI package.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
