# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ShunsukeSuzuki.AsciinemaTrim
PackageVersion: 0.1.2
InstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2025-04-20
Installers:
- Architecture: x64
  InstallerUrl: https://winget.tplant.com.au/download/m/ShunsukeSuzuki/AsciinemaTrim/0.1.2/asciinema-trim.exe
  InstallerSha256: 2643A42EA3E607AFFA66E949185483370B6FE433FF79B32DF6FC308BBAA67BED
ManifestType: installer
ManifestVersion: 1.9.0
