# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.SupportCenter
PackageVersion: 5.2403.1209.1000
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
