# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.SupportCenter
PackageVersion: 5.2403.1209.1000
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: ConfigMgr Support Center
License: Proprietary
ShortDescription: Use Support Center for client troubleshooting, real-time log viewing, or capturing the state of a Configuration Manager client computer for later analysis.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
