# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.SupportCenter
PackageVersion: 5.2403.1209.1000
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{69237C81-2AB9-4E98-B1AE-693DD9B070A8}'
AppsAndFeaturesEntries:
- DisplayName: Configuration Manager Support Center
  ProductCode: '{69237C81-2AB9-4E98-B1AE-693DD9B070A8}'
  UpgradeCode: '{8522D0C9-D2A0-4AF7-849A-6796E5D179DB}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Configuration Manager Support Center'
Installers:
- Architecture: x86
  InstallerUrl: https://winget.tplant.com.au/download/m/Microsoft/ConfigMgr/SupportCenter/5.2403.1209.1000/SupportCenterInstaller.msi
  InstallerSha256: FE4BEAB14421D379010F1E853996F90058F940E247FCCDE92129810201F3F639
ManifestType: installer
ManifestVersion: 1.10.0
