# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.EventLogExpert
PackageVersion: 25.4.1.1004
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: EventLogExpert
License: MIT
ShortDescription: A Windows Event Log viewer for tech support and IT professionals.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
