# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.EventLogExpert
PackageVersion: 25.4.1.1004
Platform:
- Windows.Desktop
- Windows.Universal
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
FileExtensions:
- evtx
PackageFamilyName: eventlogexpert_8wekyb3d8bbwe
RestrictedCapabilities:
- packageManagement
- runFullTrust
ReleaseDate: 2025-04-01
AppsAndFeaturesEntries:
- DisplayName: Windows Event Log
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\WindowsApps\eventlogexpert_25.4.1.1004_x64__8wekyb3d8bbwe'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/EventLogExpert/releases/download/v25.4.1.1004/EventLogExpert_25.4.1.1004_x64.msix
  InstallerSha256: AEC301855C4E3376B41546A68B8D1A08F424CA69637852F9CE20928E5527B5F9
  SignatureSha256: 7F1BC45CBBD146CD0327D8ECD0FC5195ED001777FF7F126E0B717336EFE741FD
ManifestType: installer
ManifestVersion: 1.9.0
