# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.RemoteBannerApp
PackageVersion: 2.0.02931.136
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Microsoft Remote Banner App
License: Proprietary
ShortDescription: This tool is used for displaying classified banners on specific applications on a desktop.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
