# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: AIMP.AIMP
PackageVersion: 5.40.2703
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
