# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: AIMP.AIMP
PackageVersion: 5.40.2703
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /AUTO /SILENT
  SilentWithProgress: /AUTO
UpgradeBehavior: install
ReleaseDate: 2025-12-24
Installers:
- Architecture: x86
  InstallerUrl: https://www.aimp.ru/?do=download.file&id=4
  InstallerSha256: 50C3AEDAB55AA7263284D9761868E344E7F174AFF205F5AF95E30548DAB9CA30
- Architecture: x64
  InstallerUrl: https://www.aimp.ru/?do=download.file&id=3
  InstallerSha256: 080981925A962749E2B99B10B6A199204EF4FC9D5B836DCA7415DB96E77EF8EF
ManifestType: installer
ManifestVersion: 1.10.0
