# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.Orca
PackageVersion: 5.0.10011.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Windows Orca
PackageUrl: https://go.microsoft.com/fwlink/?linkid=2320054
License: Proprietary
ShortDescription: Orca.exe is a database table editor for creating and editing Windows Installer packages and merge modules.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
