# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.IISExpress
PackageVersion: 10.0.2001.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: IIS Express
License: Proprietary
ShortDescription: IIS 10.0 Express is a simple and self-contained version of IIS 10.0 that is optimized for developers.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
