# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.DeploymentMonitoring
PackageVersion: 5.0.9128.1007
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: ConfigMgr Deployment Monitoring Tool
PackageUrl: https://go.microsoft.com/fwlink/?linkid=2237687
License: Proprietary
Copyright: Copyright (C) Microsoft Corporation. All rights reserved.
ShortDescription: The Deployment Monitoring Tool is one of the Configuration Manager tools. It's a graphical user interface designed to assist in troubleshooting application, software update, and configuration baseline deployments on a Configuration Manager client.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
