# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.DeploymentMonitoring
PackageVersion: 5.0.9128.1007
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
